### ISSUE TITLE
Python syntax

### ISSUE THREAD

**Issue by Alexey-T** [vikonix/multitextor#13]
Python allows strings with triple quotes. they are multi-line.
not supported.

![Screenshot from 2021-08-31 22-10-48](https://user-images.githubusercontent.com/4154978/131561947-3fb67a91-bbaf-401e-98ab-f2888ee295c0.png)

**Comment by Alexey-T** [comment]
example:
```
Str = '''text
text2
text end'''

str2 = """text
text2
end"""
```

**Comment by vikonix** [comment]
Now my parser can recognize only multiline comments
fixed for '''
so those strings will be looks like comments
