### ISSUE TITLE
Don't build in Slackware current

### ISSUE THREAD

**Issue by free-archer** [vikonix/multitextor#16]
I checked all the depends.

But i can't compile it.

`root@sl-alive:/tmp/multitextor# ./cmakegen.bat

- -- The C compiler identification is GNU 11.2.0
- -- The CXX compiler identification is GNU 11.2.0
- -- Detecting C compiler ABI info
- -- Detecting C compiler ABI info - done
- -- Check for working C compiler: /usr/bin/cc - skipped
- -- Detecting C compile features
- -- Detecting C compile features - done
- -- Detecting CXX compiler ABI info
- -- Detecting CXX compiler ABI info - done
- -- Check for working CXX compiler: /usr/bin/c++ - skipped
- -- Detecting CXX compile features
- -- Detecting CXX compile features - done
- -- Looking for pthread.h
- -- Looking for pthread.h - found
- -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
- -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
- -- Looking for pthread_create in pthreads
- -- Looking for pthread_create in pthreads - not found
- -- Looking for pthread_create in pthread
- -- Looking for pthread_create in pthread - found
- -- Found Threads: TRUE  
- -- Configuring done
- -- Generating done

`

[  6%] Building CXX object Utils/CMakeFiles/UtilsLib.dir/src/Clipboard.cpp.o
[  8%] Building CXX object Utils/CMakeFiles/UtilsLib.dir/src/CpConverter.cpp.o
In file included from /tmp/multitextor/Utils/src/CpConverter.cpp:28:
/tmp/multitextor/Utils/inc/utils/IntervalMap.h: In constructor ‘_Utils::IntervalMap<TKey, TVal>::IntervalMap(TVal)’:
/tmp/multitextor/Utils/inc/utils/IntervalMap.h:44:22: error: ‘numeric_limits’ is not a member of ‘std’
   44 |         m_diaps[std::numeric_limits<TKey>::lowest()] = value;
      |                      ^~~~~~~~~~~~~~
/tmp/multitextor/Utils/inc/utils/IntervalMap.h:44:41: error: expected primary-expression before ‘>’ token
   44 |         m_diaps[std::numeric_limits<TKey>::lowest()] = value;
      |                                         ^
/tmp/multitextor/Utils/inc/utils/IntervalMap.h:44:44: error: ‘::lowest’ has not been declared
   44 |         m_diaps[std::numeric_limits<TKey>::lowest()] = value;
      |                                            ^~~~~~
In file included from /tmp/multitextor/Utils/src/CpConverter.cpp:30:
/tmp/multitextor/ThirdParty/inc/widecharwidth/widechar_width.h: At global scope:
/tmp/multitextor/ThirdParty/inc/widecharwidth/widechar_width.h:533:5: warning: ‘int {anonymous}::widechar_wcwidth(uint32_t)’ defined but not used [-Wunused-function]
  533 | int widechar_wcwidth(uint32_t c) {
      |     ^~~~~~~~~~~~~~~~
make[2]: *** [Utils/CMakeFiles/UtilsLib.dir/build.make:90: Utils/CMakeFiles/UtilsLib.dir/src/CpConverter.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:196: Utils/CMakeFiles/UtilsLib.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

What can I do?

**Comment by vikonix** [comment]
must be fixed
