### ISSUE TITLE
editor cannot highlight HTML comments

### ISSUE THREAD

**Issue by Alexey-T** [vikonix/multitextor#18]
[new.zip](https://github.com/vikonix/multitextor/files/7101407/new.zip)

Comments are not hilited:
![Screenshot from 2021-09-02 22-51-31](https://user-images.githubusercontent.com/4154978/131907319-35e860b6-3a1b-483b-9dbe-cff0a571bdca.png)

**Comment by vikonix** [comment]
I have not created html parsing template. And you see just simple text layout.
Try to change syntax with XML.

**Comment by Alexey-T** [comment]
in XML syntax you hillite inly internal part of comment without < >.
not OK.

**Comment by vikonix** [comment]
fixed )
