### ISSUE TITLE
new version don't show any files/dirs in the Open dialog

### ISSUE THREAD

**Issue by Alexey-T** [vikonix/multitextor#19]
after updating via 'snap install --edge multitextor', I got empty file list in Open dialog!
I tried `*` and `*.*` masks. still empty.
I call dialog by F3.
![Screenshot from 2021-09-07 21-10-37](https://user-images.githubusercontent.com/4154978/132391486-15ff109b-e0e0-4b9f-8812-5d282be819cc.png)
![Screenshot from 2021-09-07 21-10-45](https://user-images.githubusercontent.com/4154978/132391504-0e00d4f6-8052-4e2d-8476-e84c63a0ed60.png)

**Comment by Alexey-T** [comment]
Also command 'multitextor torrent.cpp' shows file as empty!
![Screenshot from 2021-09-07 21-13-48](https://user-images.githubusercontent.com/4154978/132391750-803a82b0-85ae-4e09-82f9-811e8e77206a.png)

**Comment by vikonix** [comment]
It's very strange.
check snap version
"~/snap/multitextor/~current"
and "/snap/multitextor/~current"
must be 462

try to remove "~/snap/multitextor" and run editor one more

Do you use same user name, maybe not have rights?
Empty list will be if not have rights.
File empty so it was opened as new.

**Comment by Alexey-T** [comment]
```
user@PC:~/snap/multitextor$ ll
total 16
drwxr-xr-x  4 user user 4096 сен  7 21:09 ./
drwxr-xr-x 13 user user 4096 авг 31 15:15 ../
drwxr-xr-x  2 user user 4096 сен  7 21:09 462/
drwxr-xr-x  2 user user 4096 сен  7 21:09 common/
lrwxrwxrwx  1 user user    3 сен  7 21:09 current -> 462/
```
I removed it already before reinstall.

**Comment by vikonix** [comment]
I think it's restriction problem.
try to use --devmode for installation
>snap refresh --edge --devmode multitextor

now I have trying to get a classic access for snap

**Comment by Alexey-T** [comment]
What should i do?

**Comment by vikonix** [comment]
just add --devmode option for installation

**Comment by Alexey-T** [comment]
then it's solved.

**Comment by vikonix** [comment]
snap returned to develop access
