### ISSUE TITLE
Number prefixes in *.lex files

### ISSUE THREAD

**Issue by Alexey-T** [vikonix/multitextor#6]
```
    "1_LanguageName": "C++",
    "2_FileExtentions": "*.c;*.cc;*.cpp;*.h;*.hpp",
    "3_Delimiters": "[]{}();",
    "4_NameSymbols": "$",
    "5_SpecialCombination": [],
    "6_LineComments": [
      "//"
    ],
    "7_OpenComments": [
      "/*"
    ],
    "8_ClosedComments": [
      "*/"
    ],
    "9_ToggledComments": [],
```
It's weird. Numbers are not needed here, you can read words. Numbers make it hard to read.

**Comment by vikonix** [comment]
You are right except only one. Numbers help to make options sorting.
Without it I have a problem when I use any Json library. Them use lexical sorting and options will mixed in strange order for users.

**Comment by Alexey-T** [comment]
but proper lib must keep order of JSON items when you add them.

**Comment by vikonix** [comment]
No. They uses a some sort of map for storing data. Like a tree map.
